# Generated by Django 2.1.5 on 2019-12-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrollBook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='troll',
            name='image',
            field=models.BinaryField(blank=True),
        ),
    ]
